# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
##########################################################################
# This workflow will build a Java project with Gradle and
# cache/restore any dependencies to improve the workflow execution time
##########################################################################
name: 'Build-Test'
env:
  JAVA_HOME: '/__t/Java_Adopt_jdk/11.0.16-8/x64/bin/java'
on:
  push:
    branches:
      - 'master'
      - 'release*'
      - '*'

  pull_request:
    branches:
      - 'master'
      - 'release*'
      - '*'

jobs:
  # This job will perform build and tests on project package.
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Step 1 - Setup Gradle and Execute Dry Run
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1
          arguments: |
            build
            --dry-run

      - name: Step 2 - Verify Repository Contents
        run: |
          ls

      - name: Step 3 - Execute Package build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1
          arguments: |
            build
            test

      - name: Step 4 - Execute Package Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1
          arguments: |
            test

      - name: Step 5 - Setup a cache for Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Step 6 - Persist build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: csci4320-artifact
          path: build/libs

      - name: Step 7 - Persist Test Results
        uses: actions/upload-artifact@v2
        with:
          name: csci4320-test-results
          path: build/reports/tests

      - name: Step 8 - Copy to Tests Dir
        run: |
          cp -R build/reports/tests  docs/

  # This job will attempt to merge only on success Build job completion.
  merge-me:
    # Automatic Merge will not occur unless a successful Build and Test Run
    # List all required job names here.
    needs:
      - Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - # It is often a desired behavior to merge only when a workflow execution
        # succeeds. This can be changed as needed.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge With Master On Success
        uses: ridedott/merge-me-action@v2
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, you can use `SOME_RANDOM_TOKEN_STRING`.
          # Since this repository has no protected branches we will omit
          # this part of the step.
          GITHUB_TOKEN: ${{ secrets.BRANCH_ACCESS_TOKEN }}